spring.application.name=pixelpals
spring.config.import=file:backend/env.properties
server.port=8443

logging.level.org.springframework=DEBUG
#spring.jpa.properties.hibernate.default_schema=public
#spring.datasource.url=jdbc:postgresql://localhost:5432/pixelpals
#spring.datasource.username=${POSTGRES_USER}
#spring.datasource.password=${POSTGRES_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE_NAME}

cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.api_secret=${CLOUDINARY_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USER}
spring.mail.password=${GMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.debug=true


# JWT Configuration
jwt.duration=900000 # 15 minuti in millisecondi
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
mongodb+srv://libaleoncini:Ln9OtaEddCiVipro@pixelpals.dcdep42.mongodb.net/?retryWrites=true&w=majority&appName=pixelpals

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# OAuth2 Discord
spring.security.oauth2.client.registration.discord.client-id=${DISCORD_CLIENT_ID}
spring.security.oauth2.client.registration.discord.client-secret=${DISCORD_CLIENT_SECRET}
spring.security.oauth2.client.registration.discord.scope=identify,email
spring.security.oauth2.client.registration.discord.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.discord.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.discord.client-name=Discord

spring.security.oauth2.client.provider.discord.authorization-uri=https://discord.com/api/oauth2/authorize
spring.security.oauth2.client.provider.discord.token-uri=https://discord.com/api/oauth2/token
spring.security.oauth2.client.provider.discord.user-info-uri=https://discord.com/api/users/@me
spring.security.oauth2.client.provider.discord.user-name-attribute=id
# src/main/resources/application.properties


# Abilita SSL per il server integrato di Spring Boot


# Abilita SSL
server.ssl.enabled=true

# *** CAMBIA IL TIPO DI KEY STORE IN PKCS12 ***
server.ssl.key-store-type=PKCS12

# *** PUNTA AL NUOVO FILE p12 ***
server.ssl.key-store=classpath:ssl/keystore.p12
server.ssl.key-store-password=mysecretpassword
server.ssl.key-alias=myapp-cert
