spring.application.name=pixelpals
spring.config.import=file:backend/env.properties
server.port=8080

logging.level.org.springframework=DEBUG
#spring.jpa.properties.hibernate.default_schema=public
#spring.datasource.url=jdbc:postgresql://localhost:5432/pixelpals
#spring.datasource.username=${POSTGRES_USER}
#spring.datasource.password=${POSTGRES_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE_NAME}

cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.api_secret=${CLOUDINARY_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USER}
spring.mail.password=${GMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.debug=true


# JWT Configuration
jwt.duration=900000 # 15 minuti in millisecondi
jwt.secret=${JWT_SECRET}
mongodb+srv://libaleoncini:Ln9OtaEddCiVipro@pixelpals.dcdep42.mongodb.net/?retryWrites=true&w=majority&appName=pixelpals